kind: pipeline
type: docker
name: benchmark
node:
  node: hz-cdr

volumes:
- name: dockersock
  temp: {}

services:
- name: infra
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - sleep 10 # give docker enough time to start
  - docker compose up -d

steps:
- name: test 
  image: docker:dind
  environment:
    LICENSE:
      from_secret: LICENSE
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - sleep 10 # give docker enough time to start
  - docker ps -a
  - sleep 5 # give docker enough time to start