name: perf

volumes:
  pgdata:
  promdata:
  tgzdata:

services:
  postgres:
    container_name: perf-postgres
    image: postgres:18
    command: postgres -c config_file=/postgres.conf
    ports:
      - "13020:5432"
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 30G
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -U postgres
      interval: 3s
      start_period: 10s
    volumes:
      - pgdata:/var/lib/postgresql/data:delegated
      - ./infra/postgres/init:/docker-entrypoint-initdb.d
      - ./infra/postgres/postgres.conf:/postgres.conf
  aidbox-indexer:
    container_name: perf-aidbox-idx
    depends_on:
      aidbox:
        condition: service_healthy
      postgres:
        condition: service_healthy
    image: postgres:17
    command:
      - bash
      - -c
      - |
        psql -v ON_ERROR_STOP=1 <<-EOF
          -- Organization indexes
          CREATE INDEX CONCURRENTLY IF NOT EXISTS "organization_resource" ON "organization" USING gin (resource jsonb_ops);
          -- Location indexes
          CREATE INDEX CONCURRENTLY IF NOT EXISTS "location_resource" ON "location" USING gin (resource jsonb_ops);
          -- Practitioner indexes
          CREATE INDEX CONCURRENTLY IF NOT EXISTS "practitioner_resource" ON "practitioner" USING gin (resource jsonb_ops);
          -- PractitionerRole indexes
          CREATE INDEX CONCURRENTLY IF NOT EXISTS "practitionerrole_resource" ON "practitionerrole" USING gin (resource jsonb_ops);
        EOF
        echo "Indexes created successfully"
        # Keep container running
        sleep infinity
    environment:
      PGDATABASE: aidbox
      PGHOST: postgres
      PGPASSWORD: postgres
      PGUSER: postgres

  postgres-exporter:
    container_name: perf-postgres-exporter
    image: quay.io/prometheuscommunity/postgres-exporter
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATA_SOURCE_PASS: postgres
      DATA_SOURCE_USER: postgres
      DATA_SOURCE_URI: postgres:5432/postgres?sslmode=disable
    healthcheck:
      test: wget -O - http://localhost:9187/metrics
      interval: 10s
      start_period: 10s
      timeout: 5s
      retries: 3

  aidbox:
    container_name: perf-aidbox
    image: healthsamurai/aidboxone:edge
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 20G
    volumes:
      - ./infra/aidbox/initbundle.json:/tmp/initbundle.json
    environment:
      BOX_ADMIN_PASSWORD: secret
      BOX_BOOTSTRAP_FHIR_PACKAGES: hl7.fhir.r4.core#4.0.1
      BOX_DB_DATABASE: aidbox
      BOX_DB_HOST: postgres
      BOX_DB_PASSWORD: postgres
      BOX_DB_USER: postgres
      BOX_DB_POOL_MAXIMUM__POOL__SIZE: 32
      BOX_WEB_THREAD: 16
      BOX_FHIR_COMPLIANT_MODE: true
      BOX_FHIR_CORRECT_AIDBOX_FORMAT: true
      BOX_FHIR_CREATEDAT_URL: https://aidbox.app/ex/createdAt
      BOX_FHIR_SCHEMA_VALIDATION: true
      BOX_FHIR_SEARCH_AUTHORIZE_INLINE_REQUESTS: true
      BOX_FHIR_SEARCH_COMPARISONS: true
      BOX_FHIR_TERMINOLOGY_SERVICE_BASE_URL: https://tx.health-samurai.io/fhir
      BOX_METRICS_PORT: 8379
      BOX_FHIR_LEGACY_FCE_PACKAGE: app.aidbox.main#0.0.1
      BOX_INIT_BUNDLE: file:///tmp/initbundle.json
      BOX_ROOT_CLIENT_SECRET: secret
      BOX_SEARCH_INCLUDE_CONFORMANT: true
      BOX_SECURITY_DEV_MODE: true
      BOX_SETTINGS_MODE: read-write
      BOX_WEB_BASE_URL: http://localhost:8080
      BOX_WEB_MAX_BODY: 209715200
      BOX_WEB_PORT: 8080
      BOX_FHIR_SEARCH_DEFAULT_PARAMS_TOTAL: none
      JAVA_OPTS: "-XX:MaxRAMPercentage=80 -XshowSettings:vm"
    healthcheck:
      test: curl -f http://localhost:8080/health
      interval: 30s
      start_period: 30s
      retries: 10
    ports:
      - "13080:8080"

  cadvisor:
    container_name: perf-cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  grafana:
    container_name: perf-grafana
    image: grafana/grafana-oss
    environment:
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_BASIC_ENABLED: false
    healthcheck:
      test: curl http://localhost:3000/api/health
      interval: 5s
      start_period: 30s
    ports:
      - "13000:3000"
    volumes:
      - ./infra/grafana:/etc/grafana/provisioning:ro

  hapi:
    container_name: perf-hapi
    image: hapiproject/hapi:latest
    entrypoint:
      - java
      - -XX:MaxRAMPercentage=80
      - -XshowSettings:vm
      - --class-path
      - /app/main.war
      - -Dloader.path=main.war!/WEB-INF/classes/,main.war!/WEB-INF/,/app/extra-classes
      - org.springframework.boot.loader.PropertiesLauncher
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 20G
    ports:
      - "13090:8080"
    volumes:
      - ./infra/hapi/application.yaml:/app/config/application.yaml:ro

  hapi-checker:
    container_name: perf-hapi-hc
    image: curlimages/curl
    command: ["-c", "trap : TERM INT; sleep infinity & wait"]
    depends_on:
      hapi:
        condition: service_started
    entrypoint: /bin/sh
    healthcheck:
      test: curl -f http://hapi:8080/actuator/health/readiness
      interval: 10s
      start_period: 30s
      retries: 10

  medplum:
    image: medplum/medplum-server
    command:
      - file:/srv/config.json
    deploy:
      replicas: 8
      resources:
        limits:
          cpus: '1'
          memory: 3G
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./infra/medplum:/srv
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          'fetch("http://localhost:8103/healthcheck").then(r => r.json()).then(console.log).catch(() => { process.exit(1); })',
        ]
      interval: 10s
      timeout: 1s
      retries: 10

  prometheus:
    container_name: perf-prometheus
    image: prom/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --enable-feature=native-histograms
      - --storage.tsdb.path=/prometheus
      - --web.enable-remote-write-receiver
    healthcheck:
      test: wget -O - http://localhost:9090/-/ready
      interval: 5s
      start_period: 5s
    ports:
      - "13010:9090"
    volumes:
      - promdata:/prometheus
      - ./infra/prometheus/config.yaml:/etc/prometheus/prometheus.yml

  k6:
    container_name: perf-k6
    image: grafana/k6
    depends_on:
      aidbox:
        condition: service_healthy
      medplum:
        condition: service_healthy
      hapi-checker:
        condition: service_healthy
    profiles:
      - donotstart
    volumes:
      - ./k6:/k6
      - ./runner.sh:/runner.sh:ro

  redis:
    container_name: perf-redis
    image: redis:latest
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      start_period: 10s
      timeout: 5s
      retries: 5

  tgz:
    container_name: perf-tgz
    build:
      context: infra/tgz
    command:
      - "https://storage.googleapis.com/aidbox-public/synthea/performance/bulk_1k.tar.gz"
    volumes:
      - tgzdata:/data
    working_dir: /data


