name: perf

networks:
  global:
    driver: bridge

volumes:
  pgdata:
  promdata:
  redisdata:
  tgzdata:

services:
  aidbox:
    container_name: perf-aidbox
    image: healthsamurai/aidboxone:edge
    pull_policy: always
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 6G
    environment:
      BOX_ADMIN_PASSWORD: secret
      BOX_BOOTSTRAP_FHIR_PACKAGES: hl7.fhir.r4.core#4.0.1
      BOX_DB_DATABASE: aidbox
      BOX_DB_HOST: postgres
      BOX_DB_PASSWORD: postgres
      BOX_DB_USER: postgres
      BOX_DB_POOL_MAXIMUM__POOL__SIZE: 16
      BOX_WEB_THREAD: 8
      BOX_FHIR_COMPLIANT_MODE: true
      BOX_FHIR_CORRECT_AIDBOX_FORMAT: true
      BOX_FHIR_CREATEDAT_URL: https://aidbox.app/ex/createdAt
      BOX_FHIR_SCHEMA_VALIDATION: true
      BOX_FHIR_SEARCH_AUTHORIZE_INLINE_REQUESTS: true
      BOX_FHIR_SEARCH_COMPARISONS: true
      BOX_FHIR_TERMINOLOGY_SERVICE_BASE_URL: https://tx.health-samurai.io/fhir
      BOX_METRICS_PORT: 8379
      BOX_ROOT_CLIENT_SECRET: secret
      BOX_SEARCH_INCLUDE_CONFORMANT: true
      BOX_SECURITY_DEV_MODE: true
      BOX_SETTINGS_MODE: read-write
      BOX_WEB_BASE_URL: http://localhost:8080
      BOX_WEB_PORT: 8080
      JAVA_OPTS: "-XX:MaxRAMPercentage=75 -XshowSettings:vm"
    healthcheck:
      test: curl -f http://localhost:8080/health
      interval: 30s
      start_period: 30s
      retries: 10
    networks:
      - global
    ports:
      - "13080:8080"

  aidbox-indexer:
    container_name: perf-aidbox-idx
    depends_on:
      aidbox:
        condition: service_healthy
      postgres:
        condition: service_healthy
    image: postgres:17
    command:
      - bash
      - -c
      - |
        psql -v ON_ERROR_STOP=1 <<-EOF
          CREATE INDEX IF NOT EXISTS claim_resource_idx ON Claim USING GIN (resource jsonb_path_ops);
          CREATE INDEX IF NOT EXISTS encounter_resource_idx ON Encounter USING GIN (resource jsonb_path_ops);
          CREATE INDEX IF NOT EXISTS explanation_of_benefit_resource_idx ON ExplanationOfBenefit USING GIN (resource jsonb_path_ops);
          CREATE INDEX IF NOT EXISTS location_resource_idx ON Location USING GIN (resource jsonb_path_ops);
          CREATE INDEX IF NOT EXISTS medication_request_resource_idx ON MedicationRequest USING GIN (resource jsonb_path_ops);
          CREATE INDEX IF NOT EXISTS observation_resource_idx ON Observation USING GIN (resource jsonb_path_ops);
          CREATE INDEX IF NOT EXISTS organization_resource_idx ON Organization USING GIN (resource jsonb_path_ops);
          CREATE INDEX IF NOT EXISTS patient_resource_idx ON Patient USING GIN (resource jsonb_path_ops);
          CREATE INDEX IF NOT EXISTS practitioner_resource_idx ON Practitioner USING GIN (resource jsonb_path_ops);
        EOF
    environment:
      PGDATABASE: aidbox
      PGHOST: postgres
      PGPASSWORD: postgres
      PGUSER: postgres
    networks:
      - global
    volumes:
      - pgdata:/var/lib/postgresql/data:delegated

  cadvisor:
    container_name: perf-cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    networks:
      - global
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  grafana:
    container_name: perf-grafana
    image: grafana/grafana-oss
    depends_on:
      prometheus:
        condition: service_healthy
    environment:
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_BASIC_ENABLED: false
    healthcheck:
      test: curl http://localhost:3000/api/health
      interval: 5s
      start_period: 30s
    networks:
      - global
    ports:
      - "13000:3000"
    volumes:
      - ./grafana:/etc/grafana/provisioning:ro

  hapi:
    container_name: perf-hapi
    image: hapiproject/hapi:latest
    entrypoint:
      - java
      - -XX:MaxRAMPercentage=75
      - -XshowSettings:vm
      - --class-path
      - /app/main.war
      - -Dloader.path=main.war!/WEB-INF/classes/,main.war!/WEB-INF/,/app/extra-classes
      - org.springframework.boot.loader.PropertiesLauncher
    pull_policy: always
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 6G
    networks:
      - global
    ports:
      - "13090:8080"
    volumes:
      - ./hapi/application.yaml:/app/config/application.yaml:ro
      - ./curl:/mnt:ro

  hapi-checker:
    container_name: perf-hapi-hc
    image: curlimages/curl
    command: ["-c", "trap : TERM INT; sleep infinity & wait"]
    depends_on:
      hapi:
        condition: service_started
    entrypoint: /bin/sh
    healthcheck:
      test: curl -f http://hapi:8080/actuator/health/readiness
      interval: 10s
      start_period: 30s
      retries: 10
    networks:
      - global

  k6:
    container_name: perf-k6
    image: grafana/k6
    depends_on:
      aidbox:
        condition: service_healthy
      hapi-checker:
        condition: service_healthy
      medplum-checker:
        condition: service_healthy
      prometheus:
        condition: service_healthy
      tgz:
        condition: service_healthy
    entrypoint: /run.sh
    environment:
      BUNDLE_URL: http://tgz:8080
      CI: "${CI}"
      K6_PROMETHEUS_RW_SERVER_URL: http://prometheus:9090/api/v1/write
      K6_PROMETHEUS_RW_TREND_STATS: p(95),p(99),min,max
      OUTDIR: /results
    networks:
      - global
    profiles:
      - donotstart
    tmpfs:
      - /auth
    volumes:
      - ./run.sh:/run.sh:ro
      - ./test:/test
      - ./results:/results
    working_dir: /test

  medplum-x:
    container_name: perf-medplum-x
    image: medplum/medplum-server
    pull_policy: always
    command:
      - file:/srv/config.json
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - global
    volumes:
      - ./medplum:/srv

  medplum-checker:
    container_name: perf-medplum-hc
    image: curlimages/curl
    command: ["-c", "trap : TERM INT; sleep infinity & wait"]
    depends_on:
      medplum-x:
        condition: service_started
    entrypoint: /bin/sh
    healthcheck:
      test: curl -f http://medplum-x:8103/healthcheck
      interval: 10s
      start_period: 30s
      retries: 10
    networks:
      - global

  medplum:
    image: medplum/medplum-server
    pull_policy: always
    command:
      - file:/srv/config.json
    deploy:
      replicas: 8
      resources:
        limits:
          cpus: 1
          memory: 1G
      restart_policy:
        condition: on-failure
        delay: 10s
    depends_on:
      medplum-x:
        condition: service_started
      medplum-checker:
        condition: service_healthy
    networks:
      - global
    volumes:
      - ./medplum:/srv


  postgres:
    container_name: perf-postgres
    image: postgres:17
    command: postgres -c config_file=/postgres.conf
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 8G
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -U postgres
      interval: 3s
      start_period: 10s
    networks:
      - global
    volumes:
      - pgdata:/var/lib/postgresql/data:delegated
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./postgres/postgres.conf:/postgres.conf

  prometheus:
    container_name: perf-prometheus
    image: prom/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --enable-feature=native-histograms
      - --storage.tsdb.path=/prometheus
      - --web.enable-remote-write-receiver
    healthcheck:
      test: wget -O - http://localhost:9090/-/ready
      interval: 5s
      start_period: 5s
    networks:
      - global
    volumes:
      - promdata:/prometheus
      - ./prometheus/config.yaml:/etc/prometheus/prometheus.yml

  readiness:
    container_name: perf-readiness
    image: bash
    command:
      - -c
      - echo -e "\n\nAll services are up and running\n\n"
    depends_on:
      aidbox:
        condition: service_healthy
      hapi-checker:
        condition: service_healthy
      medplum-checker:
        condition: service_healthy
      prometheus:
        condition: service_healthy
      tgz:
        condition: service_healthy

  redis:
    container_name: perf-redis
    image: redis:latest
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      start_period: 10s
      timeout: 5s
      retries: 5
    networks:
      - global
    volumes:
      - redisdata:/data

  reporter:
    container_name: perf-reporter
    command:
      - --bun
      - /reporter/index.js
    environment:
      METRICS_URL: "http://prometheus:9090"
      DASHBOARD_FILE: /dashboard.json
    image: oven/bun:alpine
    networks:
      - global
    profiles:
      - donotstart
    volumes:
      - ./grafana/dashboards/perf.json:/dashboard.json:ro
      - ./reporter:/reporter
      - ./results:/results
    working_dir: /results

  tgz:
    container_name: perf-tgz
    build:
      context: tgz
    command:
      - "https://storage.googleapis.com/aidbox-public/synthea/performance/bulk_1k.tar.gz"
    networks:
      - global
    ports:
      - "13081:8080"
    volumes:
      - tgzdata:/data
    working_dir: /data

  update-report:
    container_name: perf-update-report
    image: alpine:latest
    environment:
      SSH_KEY: "${SSH_KEY}"
    command:
      - /bin/sh
      - -ec
      - |
        apk add --no-cache curl git jq openssh-client
        mkdir ~/.ssh
        echo $SSH_KEY | sed 's/\^/\'$'\n''/g' > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        curl --silent https://api.github.com/meta  | jq --raw-output '"github.com "+.ssh_keys[]' >> ~/.ssh/known_hosts
        git clone --single-branch --branch gh-pages git@github.com:HealthSamurai/fhir-server-performance-benchmark.git report
        git config --global --add safe.directory /srv/report
        git config --global user.email "ci@health-samurai.io"
        git config --global user.name "CI"
        cp -v results/reports/* report/reports/
        cp -v results/snapshots/* report/snapshots/
        jq ". += [$(cat results/last-run.json)]" report/runids.json > report/runids.json.tmp
        mv report/runids.json.tmp report/runids.json
        RUN_ID=$(jq -r '.runid' results/last-run.json)
        cd report
        git add .
        git commit -m "Add run ${RUN_ID}"
        git push origin gh-pages
    profiles:
      - donotstart
    volumes:
      - ./results:/srv/results
    working_dir: /srv
