{
 "title": "Perf",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "runid",
    "label": "RunID",
    "query": {
     "query": "label_values(k6_http_reqs_total, runid)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(k6_http_reqs_total{runid=~\"$runid\"}[$__rate_interval])) by (fhirimpl)",
     "legendFormat": "{{fhirimpl}}"
    }
   ]
  },
  {
   "title": "RPS by RT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(k6_http_reqs_total{runid=~\"$runid\"}[$__rate_interval])) by (fhirimpl, group)",
     "legendFormat": "{{fhirimpl}}{{group}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[$__rate_interval])) by (name) *100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "AVG RPS",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(k6_http_reqs_total{runid=~\"$runid\"}[$__rate_interval])) by (fhirimpl, scenario)",
     "legendFormat": "{{fhirimpl}} / {{scenario}}"
    }
   ]
  }
 ]
}