{
 "title": "Perf",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "runid",
    "label": "RunID",
    "query": {
     "query": "label_values(k6_http_reqs_total, runid)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(k6_http_reqs_total{runid=~\"$runid\"}[$__rate_interval])) by (fhirimpl, scenario)",
     "legendFormat": "{{fhirimpl}} / {{scenario}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"perf-.+\"}[$__rate_interval])) by (name) *100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\"perf-.+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Import ResourcePerSecond",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(k6_bundle_size_total[$__rate_interval])",
     "legendFormat": "{{fhirimpl}}::{{scenario}}"
    }
   ]
  },
  {
   "title": "P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "k6_http_req_duration_p99",
     "legendFormat": "{{method}} {{fhirimpl}}{{group}}={{status}}"
    }
   ]
  },
  {
   "title": "AVG RPS",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(k6_http_reqs_total{runid=~\"$runid\"}[$__rate_interval])) by (fhirimpl, scenario)",
     "legendFormat": "{{fhirimpl}} / {{scenario}}"
    }
   ]
  }
 ]
}