global:
  scrape_interval: 10s
  scrape_timeout: 5s
  scrape_protocols:
  - PrometheusProto
  - PrometheusText0.0.4
  evaluation_interval: 10s
runtime:
  gogc: 75

scrape_configs:

  - job_name: aidbox
    static_configs:
      - targets: ["aidbox:8379"]

  - job_name: docker
    static_configs:
      - targets: ["host.docker.internal:9323"]

  - job_name: hapi
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["hapi:8080"]

  - job_name: octofhir
    metrics_path: /metrics
    static_configs:
      - targets: ["octofhir:8888"]

  - job_name: postgres
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: medplum
    static_configs:
      - targets: ["otel-collector:8889"]
